// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    CopyIcon: typeof import('./src/components/icons/CopyIcon.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Installation: typeof import('./src/components/Installation.vue')['default']
    Usage: typeof import('./src/components/Usage.vue')['default']
  }
}
